config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :questions
    resources :twitter_users do
      collection do
        get 'fetch_data' => 'twitter_users#fetch_data'
      end
    end
    resources :categories
    resources :collections
    resources :settings
    resources :tags
    resources :users, :only => [:index]
    resources :images do
      member do
        delete :remove_tag
      end
    end
    
    root 'root#index'
    get '/reset_all_votes_current_user' => 'root#reset_all_votes_current_user'
    get '/reset_email_current_user' => 'root#reset_email_current_user'
  end

  namespace :api do
    get '/downloader' => 'downloader#show'
    
    get 'tagger/images' => 'tagger#images'
    get 'tagger/finished' => 'tagger#finished'
    match 'tagger/vote' => 'tagger#vote', via: [:options]
    if Rails.env.development?
      get 'tagger/vote' => 'tagger#vote'
      post 'tagger/vote' => 'tagger#vote'
    else
      post 'tagger/vote' => 'tagger#vote'
    end

    get 'categories' => 'categories#index'
    get 'categories/:id' => 'categories#show'
    get 'collections' => 'collections#index'
    get 'collections/finished' => 'collections#finished'
    get 'collections/:id/images' => 'collections#images'
    get 'collections/twitter/:name' => 'collections#twitter'

    put 'users/add_email' => 'users#add_email'
    match 'users/add_email' => 'users#add_email', via: [:options]
    get '/twitter/retweet/:image_id' => 'twitter#retweet', constraints: {image_id: /\d+/}
    get '/twitter/fav/:image_id' => 'twitter#fav', constraints: {image_id: /\d+/}
  end

  resources :image_datas, :only => [:show]
  match 'twitter/images' => 'twitter#images', via: [:get]

  get 'i/:id' => "api/downloader#show"
  get '/auth/twitter/callback', to: 'api/twitter#create'
  get '/:twitter_name', to: redirect('#/t/%{twitter_name}'), constraints: {twitter_name: /@.*/}

end

app/models/twitter_user.rb
class TwitterUser < ActiveRecord::Base
  after_create :fetch_images
  validates :name, :presence => true
  validates :name, :uniqueness => true

  has_many :twitter_images, dependent: :destroy
  belongs_to :category

  scope :enabled, ->{where(enabled: true)}
  scope :list_order, ->{order("id DESC")}

  private
    def fetch_images
      begin
        TwitterFetcher.new(TwitterClient.instance, self).fetch!
      rescue Exception => e
        self.errors[:base] << "#{e.class} - #{e.to_s}"
        raise e
      end
    end
end

app/controllers/admin/twitter_users_controller.rb
class Admin::TwitterUsersController < Admin::AdminController
  before_action :set_twitter_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/twitter_users
  # GET /admin/twitter_users.json
  def index
    @twitter_users = TwitterUser.page(params[:page]).per(get_page_size).order("id DESC")
  end

  # GET /admin/twitter_users/1
  # GET /admin/twitter_users/1.json
  def show
  end

  # GET /admin/twitter_users/new
  def new
    @twitter_user = TwitterUser.new
  end

  # GET /admin/twitter_users/1/edit
  def edit
  end

  # POST /admin/twitter_users
  # POST /admin/twitter_users.json
  def create
    @twitter_user = TwitterUser.new(twitter_user_params)

    respond_to do |format|
      if @twitter_user.save
        format.html { redirect_to [:admin, @twitter_user], notice: 'twitter_user was successfully created.' }
        format.json { render :show, status: :created, location: @twitter_user }
      else
        format.html { render :new }
        format.json { render json: @twitter_user.errors, status: :unprocessable_entity }
      end
    end
  rescue Exception => e
    respond_to do |format|
      format.html { render :new }
      format.json { render json: @twitter_user.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /admin/twitter_users/1
  # PATCH/PUT /admin/twitter_users/1.json
  def update
    respond_to do |format|
      if @twitter_user.update(twitter_user_params)
        format.html { redirect_to [:admin, @twitter_user], notice: 'twitter_user was successfully updated.' }
        format.json { render :show, status: :ok, location: @twitter_user }
      else
        format.html { render :edit }
        format.json { render json: @twitter_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/twitter_users/1
  # DELETE /admin/twitter_users/1.json
  def destroy
    @twitter_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_twitter_users_url, notice: 'twitter_user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fetch_data
    @error = nil
    TwitterFetcher.fetch! do |error, user|
      @error = "#{error.to_s} (#{user.name})"
      break
    end

    render :layout => false

  rescue Exception => e
    @error = e
    Rails.logger.error "#{e.class} - #{e.to_s}"
    Rails.logger.error e.backtrace.join("\n")

    render :layout => false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitter_user
      @twitter_user = TwitterUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twitter_user_params
      params.require(:twitter_user).permit(:name, :enabled, :category_id)
    end
end

app/views/admin/twitter_users/_form.html.erb
<%= form_for([:admin, @twitter_user]) do |f| %>
  <% if @twitter_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twitter_user.errors.count, "error") %> prohibited this twitter_user from being saved:</h2>

      <ul>
      <% @twitter_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :readonly => !@twitter_user.new_record?,
      :disabled => !@twitter_user.new_record? %>

    <%= f.label :enabled %>
    <%= f.check_box :enabled %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select :category_id, Category.all.map{|c| [c.name, c.id]}, include_blank: true %>
  </div>

  <div class="actions g-wide--full">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/twitter_users/edit.html.erb
<h1>Editing admin_twitter_user</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @twitter_user] %> |
<%= link_to 'Back', admin_twitter_user_path %>

app/views/admin/twitter_users/fetch_data.js.erb
<% if @error %>
	alert('error: \n'+ '<%= escape_javascript(@error.to_s) %>');
<% else %>
	alert('data fetched correctly');
	window.location.reload();
<% end %>

app/views/admin/twitter_users/index.html.erb
<%= link_to 'New twitter_user', new_admin_twitter_user_path, :class => "pull-right button--primary" %>
<%= link_to 'Fetch Data from Twitter', fetch_data_admin_twitter_users_path, :remote => true, :id => "fetch-twitter-data", :class => "pull-right button--primary", :style => "margin-right: 10px;" %>

<%= paginate @twitter_users %>

<table>
  <thead>
    <tr>
      <th colspan="7"><strong>twitter_users</strong> list</th>
    </tr>
  </thead>

  <tbody>
    <% @twitter_users.each do |twitter_user| %>
      <tr>
        <td><%= twitter_user.name %></td>
        <td><%= twitter_user.twitter_images.count %></td>
        <td><%= twitter_user.category.try(:name) %></td>
        <td><%= twitter_user.enabled? ? "Enabled" : "Disabled" %></td>
        <td><%= link_to 'Show', [:admin, twitter_user] %></td>
        <td><%= link_to 'Edit', edit_admin_twitter_user_path(twitter_user) %></td>
        <td><%= link_to 'Destroy', [:admin, twitter_user], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/twitter_users/new.html.erb
<%= link_to 'Back', admin_twitter_users_path, :class => "pull-right button--secondary" %>

<h1>Add <span>new twitter users</span></h1>

<%= render 'form' %>

app/views/admin/twitter_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @twitter_user.name %>
</p>

<%= link_to 'Edit', edit_admin_twitter_user_path(@twitter_user) %> |
<%= link_to 'Back', admin_twitter_users_path %>