config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :questions
    resources :twitter_users do
      collection do
        get 'fetch_data' => 'twitter_users#fetch_data'
      end
    end
    resources :categories
    resources :collections
    resources :settings
    resources :tags
    resources :users, :only => [:index]
    resources :images do
      member do
        delete :remove_tag
      end
    end
    
    root 'root#index'
    get '/reset_all_votes_current_user' => 'root#reset_all_votes_current_user'
    get '/reset_email_current_user' => 'root#reset_email_current_user'
  end

  namespace :api do
    get '/downloader' => 'downloader#show'
    
    get 'tagger/images' => 'tagger#images'
    get 'tagger/finished' => 'tagger#finished'
    match 'tagger/vote' => 'tagger#vote', via: [:options]
    if Rails.env.development?
      get 'tagger/vote' => 'tagger#vote'
      post 'tagger/vote' => 'tagger#vote'
    else
      post 'tagger/vote' => 'tagger#vote'
    end

    get 'categories' => 'categories#index'
    get 'categories/:id' => 'categories#show'
    get 'collections' => 'collections#index'
    get 'collections/finished' => 'collections#finished'
    get 'collections/:id/images' => 'collections#images'
    get 'collections/twitter/:name' => 'collections#twitter'

    put 'users/add_email' => 'users#add_email'
    match 'users/add_email' => 'users#add_email', via: [:options]
    get '/twitter/retweet/:image_id' => 'twitter#retweet', constraints: {image_id: /\d+/}
    get '/twitter/fav/:image_id' => 'twitter#fav', constraints: {image_id: /\d+/}
  end

  resources :image_datas, :only => [:show]
  match 'twitter/images' => 'twitter#images', via: [:get]

  get 'i/:id' => "api/downloader#show"
  get '/auth/twitter/callback', to: 'api/twitter#create'
  get '/:twitter_name', to: redirect('#/t/%{twitter_name}'), constraints: {twitter_name: /@.*/}

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  validates :name, presence: true

  before_save :sort_tag_ids

  scope :enabled, ->{where(:enabled => true)}
  scope :list_order, ->{order("id DESC")}

  attr_accessor :cover

  def images
    images = Image.all
    images = tag_ids.any? ? images.where("assigned_tag_ids @> '{?}'", self.tag_ids) : images
    images = negative_tag_ids.any? ? images.where("negative_tag_ids @> '{?}'", self.negative_tag_ids) : images

    images
  end

  private
    def sort_tag_ids
      self.tag_ids = self.tag_ids.map(&:to_i)
      self.tag_ids.sort!
      self.tag_ids_will_change!

      self.negative_tag_ids = self.negative_tag_ids.map(&:to_i)
      self.negative_tag_ids.sort!
      self.negative_tag_ids_will_change!
    end
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :tags, :through => :image_tags
  belongs_to :image_data, :dependent => :destroy

  validates :name, :image_data, :presence => true
  validates :name, :uniqueness => :true

  accepts_nested_attributes_for :image_data

  before_save :sort_assigned_tag_ids, :sort_negative_tag_ids

  def add_vote! tag
    count = self.temporal_tag_ids[tag.id.to_s].to_i
    count ||= 0
    count += 1

    if !self.assigned_tag_ids.include?(tag.id)
      if count >= Setting.get_image_umbral
        self.temporal_tag_ids.delete(tag.id.to_s)
        self.temporal_tag_ids_will_change!

        self.assigned_tag_ids << tag.id
        self.assigned_tag_ids_will_change!
      else
        self.temporal_tag_ids[tag.id.to_s] = count
        self.temporal_tag_ids_will_change!
      end

      self.save!
    end
  end

  def add_negative_vote! tag
    count = self.temporal_negative_tag_ids[tag.id.to_s].to_i
    count ||= 0
    count += 1

    if !self.negative_tag_ids.include?(tag.id)
      if count >= Setting.get_negative_image_umbral
        self.temporal_negative_tag_ids.delete(tag.id.to_s)
        self.temporal_negative_tag_ids_will_change!

        self.negative_tag_ids << tag.id
        self.negative_tag_ids_will_change!
      else
        self.temporal_negative_tag_ids[tag.id.to_s] = count
        self.temporal_negative_tag_ids_will_change!
      end

      self.save!
    end
  end

  private
    def sort_assigned_tag_ids
      self.assigned_tag_ids = self.assigned_tag_ids.map(&:to_i).sort
      self.assigned_tag_ids_will_change!
    end

    def sort_negative_tag_ids
      self.negative_tag_ids = self.negative_tag_ids.map(&:to_i).sort
      self.negative_tag_ids_will_change!
    end
end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < Admin::AdminController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /admin/collections
  # GET /admin/collections.json
  def index
    @collections = Collection.page(params[:page]).per(get_page_size).order("id DESC")
  end

  # GET /admin/collections/1
  # GET /admin/collections/1.json
  def show
  end

  # GET /admin/collections/new
  def new
    @collection = Collection.new
  end

  # GET /admin/collections/1/edit
  def edit
  end

  # POST /admin/collections
  # POST /admin/collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to [:admin, @collection], notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/collections/1
  # PATCH/PUT /admin/collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to [:admin, @collection], notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/collections/1
  # DELETE /admin/collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to admin_collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params[:collection][:negative_tag_ids] ||= []
      params[:collection][:tag_ids] ||= []
      params.require(:collection).permit(:name, :enabled, :tag_ids => [], :negative_tag_ids => [])
    end
end

app/controllers/api/collections_controller.rb
class Api::CollectionsController < Api::ApiController
  def index
    selected_images = [0]

    @twitter_users = TwitterUser.list_order.enabled
    @collections = Collection.list_order.enabled
    @collections.each do |collection|
      collection.cover = collection.images.
        where("id not in (?)", selected_images).first

      selected_images << collection.cover
    end
  end

  def twitter
    @timeout = Setting.get_images_timeout
    
    if name = params[:name]
      name = name[1..-1] if name.start_with?("@")
      if @user = TwitterUser.enabled.where(:name => name).last
        all = if category = @user.category
          category.twitter_users.enabled.list_order.all
        else
          TwitterUser.enabled.list_order.all
        end

        if (index = all.index(@user)) < all.size - 1
          @next_collection_type = "twitter"
          @next_collection_id = all[index + 1].name
        else
          # if collection = Collection.enabled.list_order.first
          #   @next_collection_type = "collection"
          #   @next_collection_id = collection.id
          # end
        end
        @images = @user.twitter_images.order("tweet_id DESC")
      else
        render :nothing => true, :status => 404
      end
    else
      render :nothing => true, :status => 404
    end
  end

  def images
    @images = []
    @timeout = Setting.get_images_timeout
    @title = ""

    if collection = Collection.enabled.where(:id => params[:id]).first
      @title = collection.name
      @images = collection.images.order("id ASC")

      all = Collection.enabled.list_order.all

      if (index = all.index(collection)) < all.size - 1
        @next_collection_type = "collection"
        @next_collection_id = all[index + 1].id
      end

    end
  end

  def finished
    if !current_user.email.present?
      render :json => {ask_email: true}
    elsif !current_user.premium?
      render :json => {go_premium: true}
    else
      render :json => {go_index: true}
    end
  end

  private
    def get_page_size
      @page_size = 3
    end
end

app/views/admin/collections/_form.html.erb
<%= form_for([:admin, @collection]) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>

    <%= f.label :enabled %>
    <%= f.check_box :enabled %>
  </div>

  <p>Tags selected:</p>
  <ul class="selected-tags">
    <% @collection.tag_ids.each do |tag_id| %>
      <li class="tag" data-tag-id="<%= tag_id %>">
        <%= Tag.where(:id => tag_id).first.try(:name) %>
        <%= link_to "x", "#", :class => "remove-tag" %>
        <%= hidden_field_tag :"collection[tag_ids][]", tag_id, :id => "collection_tag_ids_#{tag_id}" %>
      </li>
    <% end %>
  </ul>

  <p>Negative tags selected:</p>
  <ul class="negative-selected-tags">
    <% @collection.negative_tag_ids.each do |tag_id| %>
      <li class="tag" data-tag-id="<%= tag_id %>">
        <%= Tag.where(:id => tag_id).first.try(:name) %>
        <%= link_to "x", "#", :class => "remove-tag" %>
        <%= hidden_field_tag :"collection[negative_tag_ids][]", tag_id, :id => "collection_negative_tag_ids_#{tag_id}" %>
      </li>
    <% end %>
  </ul>


  <div class="tags g--half">
    <%= label_tag "Search tags" %><br />
    <%= text_field_tag :"tags-filter" %>
    <ul class="filtered-tags"></ul>
  </div>

  <div class="negative-tags g--half g--last">
    <%= label_tag "Search negative tags" %><br />
    <%= text_field_tag :"negative-tags-filter" %>
    <ul class="filtered-tags"></ul>
  </div>

  <div class="actions g-wide--full">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/collections/edit.html.erb
<h1>Editing admin_collection</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @collection] %> |
<%= link_to 'Back', admin_collections_path %>

app/views/admin/collections/index.html.erb
<%= link_to 'New Collection', new_admin_collection_path, :class => "pull-right button--primary" %>

<%= paginate @collections %>

<table>
  <thead>
    <tr>
      <th colspan="5"><strong>Collections</strong> list</th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.name %></td>
        <td><%= collection.images.count %></td>
        <td><%= collection.enabled? ? "Enabled" : "Disabled" %></td>
        <td><%= link_to 'Show', [:admin, collection] %></td>
        <td><%= link_to 'Edit', edit_admin_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', [:admin, collection], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/collections/new.html.erb
<%= link_to 'Back', admin_images_path, :class => "pull-right button--secondary" %>

<h1>Add <span>new collection</span></h1>

<%= render 'form' %>

app/views/admin/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<%= link_to 'Edit', edit_admin_collection_path(@collection) %> |
<%= link_to 'Back', admin_collections_path %>