config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :questions
    resources :twitter_users do
      collection do
        get 'fetch_data' => 'twitter_users#fetch_data'
      end
    end
    resources :categories
    resources :collections
    resources :settings
    resources :tags
    resources :users, :only => [:index]
    resources :images do
      member do
        delete :remove_tag
      end
    end
    
    root 'root#index'
    get '/reset_all_votes_current_user' => 'root#reset_all_votes_current_user'
    get '/reset_email_current_user' => 'root#reset_email_current_user'
  end

  namespace :api do
    get '/downloader' => 'downloader#show'
    
    get 'tagger/images' => 'tagger#images'
    get 'tagger/finished' => 'tagger#finished'
    match 'tagger/vote' => 'tagger#vote', via: [:options]
    if Rails.env.development?
      get 'tagger/vote' => 'tagger#vote'
      post 'tagger/vote' => 'tagger#vote'
    else
      post 'tagger/vote' => 'tagger#vote'
    end

    get 'categories' => 'categories#index'
    get 'categories/:id' => 'categories#show'
    get 'collections' => 'collections#index'
    get 'collections/finished' => 'collections#finished'
    get 'collections/:id/images' => 'collections#images'
    get 'collections/twitter/:name' => 'collections#twitter'

    put 'users/add_email' => 'users#add_email'
    match 'users/add_email' => 'users#add_email', via: [:options]
    get '/twitter/retweet/:image_id' => 'twitter#retweet', constraints: {image_id: /\d+/}
    get '/twitter/fav/:image_id' => 'twitter#fav', constraints: {image_id: /\d+/}
  end

  resources :image_datas, :only => [:show]
  match 'twitter/images' => 'twitter#images', via: [:get]

  get 'i/:id' => "api/downloader#show"
  get '/auth/twitter/callback', to: 'api/twitter#create'
  get '/:twitter_name', to: redirect('#/t/%{twitter_name}'), constraints: {twitter_name: /@.*/}

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  IMAGE_UMBRAL = "image_umbral"
  NEGATIVE_IMAGE_UMBRAL = "negative_image_umbral"
  ASK_EMAIL_COUNT = "ask_email_count"
  MANY_VOTES_EMAIL_1_SUBJECT = "many_votes_email_1_subject"
  MANY_VOTES_EMAIL_1_TEXT = "many_votes_email_1_text"
  MANY_VOTES_EMAIL_1_COUNT = "many_votes_email_1_count"
  IMAGES_TIMEOUT = "images_timeout"

	validates :name, :value, :presence => true
  validates :name, :uniqueness => true

  def self.get_images_timeout
    if timeout = Setting.where(:name => IMAGES_TIMEOUT).first
      timeout.value.to_f
    else
      3
    end
  end

  def self.get_image_umbral
    if umbral = Setting.where(:name => IMAGE_UMBRAL).first
      if match = umbral.value.match(/^(\d+)%$/)
        number = match[1].to_i
        count = User.count
        ((count * number) / 100).to_i
      else
        umbral.value.to_i
      end
    else
      20
    end
  end

  def self.get_negative_image_umbral
    if umbral = Setting.where(:name => NEGATIVE_IMAGE_UMBRAL).first
      if match = umbral.value.match(/^(\d+)%$/)
        number = match[1].to_i
        count = User.count
        ((count * number) / 100).to_i
      else
        umbral.value.to_i
      end
    else
      20
    end
  end

  def self.ask_email_count
    if value = Setting.where(:name => ASK_EMAIL_COUNT).first.try(:value)
      value.to_i
    else
      25
    end
  end

  def self.get_many_votes_email_1_count
    if value = Setting.where(:name => MANY_VOTES_EMAIL_1_COUNT).first.try(:value)
      value.to_i
    else
      100
    end
  end

  def self.get_many_votes_email_1_subject
    value = Setting.where(:name => MANY_VOTES_EMAIL_1_SUBJECT).first.try(:value)
    value ||= ""
  end

  def self.get_many_votes_email_1_text
    value = Setting.where(:name => MANY_VOTES_EMAIL_1_TEXT).first.try(:value)
    value ||= ""
  end
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::AdminController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /admin/settings
  # GET /admin/settings.json
  def index
    @settings = Setting.page(params[:page]).per(get_page_size).order("id DESC")
  end

  # GET /admin/settings/1
  # GET /admin/settings/1.json
  def show
  end

  # GET /admin/settings/new
  def new
    @setting = Setting.new
  end

  # GET /admin/settings/1/edit
  def edit
  end

  # POST /admin/settings
  # POST /admin/settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to [:admin, @setting], notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/settings/1
  # PATCH/PUT /admin/settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to [:admin, @setting], notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/settings/1
  # DELETE /admin/settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to admin_settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:name, :value)
    end
end

app/views/admin/settings/_form.html.erb
<%= form_for([:admin, @setting]) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this admin_setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :readonly => !@setting.new_record? %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_area :value, :cols => 40, :rows => 5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/settings/edit.html.erb
<%= link_to 'Show', [:admin, @setting], :class => "pull-right button--secondary" %>
<%= link_to 'Back', admin_settings_path, :class => "pull-right button--secondary" %>

<h1>Edit <span>setting</span></h1>

<%= render 'form' %>

app/views/admin/settings/index.html.erb
<%= link_to 'New Setting', new_admin_setting_path, :class => "pull-right button--primary" %>

<%= paginate @settings %>

<table>
  <thead>
    <tr>
      <th colspan="5"><strong>Settings</strong> list</th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= truncate(strip_tags(setting.name), :length => 20) %></td>
        <td><%= truncate(strip_tags(setting.value), :length => 50) %></td>
        <td><%= link_to 'Show', admin_setting_path(setting) %></td>
        <td><%= link_to 'Edit', edit_admin_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', admin_setting_path(setting), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/settings/new.html.erb
<%= link_to 'Back', admin_settings_path, :class => "pull-right button--secondary" %>

<h1>Add <span>new setting</span></h1>

<%= render 'form' %>

app/views/admin/settings/show.html.erb
<%= link_to 'Edit', edit_admin_setting_path(@setting), :class => "pull-right button--primary" %>
<%= link_to 'Back', admin_settings_path, :class => "pull-right button--secondary" %>

<div class="g-medium--full g-wide--full">
	<p id="notice" class="text-center"><%= notice %></p>
</div>

<div class="show-settings">
	<p>Name: <strong><%= @setting.name %></strong></p>
	<p>Value:</p>
	<p class="huge"><%= @setting.value %></p>
</div>