config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :questions
    resources :twitter_users do
      collection do
        get 'fetch_data' => 'twitter_users#fetch_data'
      end
    end
    resources :categories
    resources :collections
    resources :settings
    resources :tags
    resources :users, :only => [:index]
    resources :images do
      member do
        delete :remove_tag
      end
    end
    
    root 'root#index'
    get '/reset_all_votes_current_user' => 'root#reset_all_votes_current_user'
    get '/reset_email_current_user' => 'root#reset_email_current_user'
  end

  namespace :api do
    get '/downloader' => 'downloader#show'
    
    get 'tagger/images' => 'tagger#images'
    get 'tagger/finished' => 'tagger#finished'
    match 'tagger/vote' => 'tagger#vote', via: [:options]
    if Rails.env.development?
      get 'tagger/vote' => 'tagger#vote'
      post 'tagger/vote' => 'tagger#vote'
    else
      post 'tagger/vote' => 'tagger#vote'
    end

    get 'categories' => 'categories#index'
    get 'categories/:id' => 'categories#show'
    get 'collections' => 'collections#index'
    get 'collections/finished' => 'collections#finished'
    get 'collections/:id/images' => 'collections#images'
    get 'collections/twitter/:name' => 'collections#twitter'

    put 'users/add_email' => 'users#add_email'
    match 'users/add_email' => 'users#add_email', via: [:options]
    get '/twitter/retweet/:image_id' => 'twitter#retweet', constraints: {image_id: /\d+/}
    get '/twitter/fav/:image_id' => 'twitter#fav', constraints: {image_id: /\d+/}
  end

  resources :image_datas, :only => [:show]
  match 'twitter/images' => 'twitter#images', via: [:get]

  get 'i/:id' => "api/downloader#show"
  get '/auth/twitter/callback', to: 'api/twitter#create'
  get '/:twitter_name', to: redirect('#/t/%{twitter_name}'), constraints: {twitter_name: /@.*/}

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :tags, :through => :image_tags
  belongs_to :image_data, :dependent => :destroy

  validates :name, :image_data, :presence => true
  validates :name, :uniqueness => :true

  accepts_nested_attributes_for :image_data

  before_save :sort_assigned_tag_ids, :sort_negative_tag_ids

  def add_vote! tag
    count = self.temporal_tag_ids[tag.id.to_s].to_i
    count ||= 0
    count += 1

    if !self.assigned_tag_ids.include?(tag.id)
      if count >= Setting.get_image_umbral
        self.temporal_tag_ids.delete(tag.id.to_s)
        self.temporal_tag_ids_will_change!

        self.assigned_tag_ids << tag.id
        self.assigned_tag_ids_will_change!
      else
        self.temporal_tag_ids[tag.id.to_s] = count
        self.temporal_tag_ids_will_change!
      end

      self.save!
    end
  end

  def add_negative_vote! tag
    count = self.temporal_negative_tag_ids[tag.id.to_s].to_i
    count ||= 0
    count += 1

    if !self.negative_tag_ids.include?(tag.id)
      if count >= Setting.get_negative_image_umbral
        self.temporal_negative_tag_ids.delete(tag.id.to_s)
        self.temporal_negative_tag_ids_will_change!

        self.negative_tag_ids << tag.id
        self.negative_tag_ids_will_change!
      else
        self.temporal_negative_tag_ids[tag.id.to_s] = count
        self.temporal_negative_tag_ids_will_change!
      end

      self.save!
    end
  end

  private
    def sort_assigned_tag_ids
      self.assigned_tag_ids = self.assigned_tag_ids.map(&:to_i).sort
      self.assigned_tag_ids_will_change!
    end

    def sort_negative_tag_ids
      self.negative_tag_ids = self.negative_tag_ids.map(&:to_i).sort
      self.negative_tag_ids_will_change!
    end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::AdminController
  before_action :set_image, only: [:show, :edit, :update, :destroy, :remove_tag]

  skip_before_filter :verify_authenticity_token, :only => [:create]

  # GET /admin/images
  # GET /admin/images.json
  def index
    @images = Image.page(params[:page]).per(get_page_size).order("id DESC")
  end

  # GET /admin/images/1
  # GET /admin/images/1.json
  def show
  end

  def remove_tag
    tag_id = params[:tag_id].to_i
    assigned_tag_ids = @image.assigned_tag_ids
    @image.assigned_tag_ids = assigned_tag_ids - [tag_id]
    @image.assigned_tag_ids_will_change!
    @image.save!

    render :js => "window.location.reload();"
  end

  # GET /admin/images/new
  def new
    @image = Image.new
  end

  # GET /admin/images/1/edit
  def edit
  end

  # POST /admin/images
  # POST /admin/images.json
  def create
    @image = Image.new(image_params)
    @image.name = image_params[:image_data_attributes][:raw_data].original_filename
    
    tags = []
    if params[:tags].present? && params[:tags].is_a?(Array)
      tags = params[:tags].map do |tag_name|
        Tag.find_or_create_by!(:name => tag_name)
      end
    end

    @image.assigned_tag_ids = tags.map(&:id)

    respond_to do |format|
      if @image.save
        format.html { redirect_to [:admin, @image], notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: [:admin, @image] }
      else
        # image_data.destroy
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/images/1
  # PATCH/PUT /admin/images/1.json
  def update
    @image.name = image_params[:image_data_attributes][:raw_data].original_filename

    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to [:admin, @image], notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @image] }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/images/1
  # DELETE /admin/images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to admin_images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit({:image_data_attributes => [:raw_data]})
    end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/views/admin/images/_form.html.erb
<%= form_for([:admin, @image], :html=> {:multipart=>true}) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this admin_image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= file_field_tag :"image[image_data_attributes][raw_data]" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/images/edit.html.erb
<%= link_to 'Show', [:admin, @image], :class => "pull-right button--secondary" %>
<%= link_to 'Back', admin_images_path, :class => "pull-right button--secondary" %>

<h1>Edit <span>image</span></h1>

<%= render 'form' %>

app/views/admin/images/index.html.erb
<%= link_to 'New Image', new_admin_image_path, :class => "pull-right button--primary" %>

<%= paginate @images %>

<table>
  <thead>
    <tr>
      <th colspan="4"><strong>Images</strong> list</th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image_tag image_data_path(image.image_data_id), :class => "list-image" %></td>
        <td><%= link_to 'Show', admin_image_path(image) %></td>
        <td><%= link_to 'Edit', edit_admin_image_path(image) %></td>
        <td><%= link_to 'Destroy', admin_image_path(image), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr>
        <td colspan="4" class="tags-list">
          <% image.assigned_tag_ids.each do |id| %>
            <span class='tag'>
              <%= Tag.where(:id => id).first.try(:name) %>
              <%= link_to "X", remove_tag_admin_image_path(image, :tag_id => id), :remote => true, :method => :delete, :"data-confirm" => "Are you sure?", :class => "delete" %>
            </span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/images/new.html.erb
<%= link_to 'Back', admin_images_path, :class => "pull-right button--secondary" %>

<h1>Add <span>new image</span></h1>

<%= render 'form' %>

app/views/admin/images/show.html.erb
<%= link_to 'Edit', edit_admin_image_path(@image), :class => "pull-right button--primary" %> 
<%= link_to 'Back', admin_images_path, :class => "pull-right button--secondary" %>

<div class="g-medium--full g-wide--full">
	<p id="notice" class="text-center"><%= notice %></p>
</div>
<div class="clear"></div>

<div class="show-image-container">
	<%= image_tag image_data_path(@image.image_data_id), :class => "show-image" %>
</div>